# Generated by Django 2.1.8 on 2019-10-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20191028_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbs',
            name='db_id',
            field=models.IntegerField(default=1),
        ),
    ]
