# Generated by Django 2.1.8 on 2019-10-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_dbs_db_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='platform_db',
        ),
    ]
