# Generated by Django 2.1.8 on 2019-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_db_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_info',
            name='db_id',
            field=models.IntegerField(default=0),
        ),
    ]
