# Generated by Django 2.1.8 on 2019-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_db_info_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_info',
            name='db_host',
            field=models.CharField(default='', max_length=50),
        ),
    ]
